;;; evil-config.el --- Evil mode configuration -*- lexical-binding: t -*-

;;; Commentary:
;; Vim emulation using Evil mode with additional packages for enhanced functionality.

;;; Code:

;; ============================================================================
;; Undo System - Required by Evil
;; ============================================================================
;;
;; edmacs-performance/phase-6-gc-and-unbounded-state: undo-tree is dropped
;; in favor of Emacs 31's native `undo-redo', which evil supports directly
;; via `evil-undo-system' (see below) with no extra package. This removes
;; `undo-tree-auto-save-history''s per-buffer-per-save disk write entirely
;; -- that setting wrote a history file to `undo-tree-history/' on every
;; save and never pruned, growing unbounded (14M/194 files at audit time,
;; including orphans for files in unrelated/deleted repos). The tradeoff:
;; cross-session undo persistence and undo-tree's branch-visualizer UI are
;; both gone -- undo history is in-memory only again, same as vanilla
;; Emacs undo. `undo-tree-history/' itself was deleted as a one-time
;; cleanup (it is gitignored, untracked, and not regenerated by anything
;; once undo-tree is gone).
;;
;; ============================================================================
;; Evil Mode
;; ============================================================================

(use-package evil
  :init
  ;; Required settings before evil loads
  (setq evil-want-integration t
        evil-want-keybinding nil  ; Required by evil-collection
        evil-want-C-u-scroll t    ; C-u scrolls up
        evil-want-C-d-scroll t    ; C-d scrolls down
        evil-want-C-i-jump nil    ; Don't use C-i for jump forward
        evil-undo-system 'undo-redo  ; native Emacs 31 undo/redo; see the
                                      ; comment above the old undo-tree
                                      ; block for why
        evil-respect-visual-line-mode t
        evil-search-module 'evil-search
        evil-split-window-below t
        evil-vsplit-window-right t)

  :config
  ;; Enable evil mode globally
  (evil-mode 1)

  ;; Use Emacs state in certain modes
  (dolist (mode '(custom-mode
                  eshell-mode
                  git-rebase-mode
                  term-mode))
    (add-to-list 'evil-emacs-state-modes mode))

  ;; Set initial states for some modes
  (evil-set-initial-state 'messages-buffer-mode 'normal)
  (evil-set-initial-state 'dashboard-mode 'normal)

  ;; Disable evil in minibuffer
  (setq evil-want-minibuffer nil))

;; ============================================================================
;; Evil Collection - Evil bindings for many modes
;; ============================================================================

(use-package evil-collection
  :after evil
  :config
  ;; Don't set evil-collection-mode-list - let it init all supported modes
  ;; Note: org-roam is not in evil-collection, so it was causing errors
  (evil-collection-init))

;; ============================================================================
;; Evil Surround - Surround text objects
;; ============================================================================

(use-package evil-surround
  :after evil
  :config
  (global-evil-surround-mode 1))

;; ============================================================================
;; Evil Commentary - Comment/uncomment with gc
;; ============================================================================

(use-package evil-commentary
  :after evil
  :diminish evil-commentary-mode
  :config
  (evil-commentary-mode 1))

;; ============================================================================
;; Evil Numbers - Increment/decrement numbers
;; ============================================================================
;;
;; `C-x' in normal state is a leaf binding to `evil-numbers/dec-at-pt'
;; (a deliberate, pre-existing vim-native mapping mirroring vim's own
;; C-a/C-x increment/decrement-at-point). Other modules that want a
;; multi-key `C-x <chord>' sequence to reach past that leaf (e.g.
;; built-ins like `project-other-tab-command' on `C-x t p', or the
;; worktree commands on `C-x v w ...') register through
;; `edmacs-evil-config-add-c-x-chord' below instead of re-defining
;; `C-x' themselves. That keeps this file the sole owner of the
;; `evil-normal-state-map' `C-x' entry no matter what order modules
;; load in or get re-evaluated in -- a later module that shadowed it
;; directly via its own `define-key'/`with-eval-after-load' would win
;; or lose purely by load order, silently reverting the extension the
;; moment load order changed.

(defvar edmacs-evil-config--c-x-chords nil
  "Alist of (KEY-STRING . COMMAND) reachable after evil's normal-state `C-x'.
Populated only via `edmacs-evil-config-add-c-x-chord'; consulted every
time the `C-x' binding is rebuilt, so registration order never
matters. KEY-STRING is a `general-key-dispatch'-style continuation
typed after `C-x', e.g. \"t p\" or \"v w s\".")

(defun edmacs-evil-config--rebuild-c-x-binding ()
  "(Re)install normal-state `C-x' from `edmacs-evil-config--c-x-chords'.
With no chords registered, `C-x' is the plain `evil-numbers/dec-at-pt'
leaf command, exactly as before this extension point existed. Once at
least one chord is registered, `C-x' instead waits (bounded by a
short grace period) to see whether one of those chords follows;
anything else -- including a timeout with nothing typed -- falls back
to `evil-numbers/dec-at-pt', simulating any unmatched keys afterward,
i.e. today's behavior for every `C-x' use the alist doesn't know
about. The dispatcher is built via `general-key-dispatch', but that's
a macro (`cl-defmacro'), and the whole point of this alist is that
its contents aren't known until some *later*-loading module (e.g.
sessions.el) registers a chord -- so the call is assembled as data and
run through `eval' rather than written as a literal macro form here,
which also means this file never needs `general' loaded yet when it
(module #2) itself loads."
  (define-key evil-normal-state-map (kbd "C-x")
    (if edmacs-evil-config--c-x-chords
        (eval
         `(general-key-dispatch 'evil-numbers/dec-at-pt
            :timeout 0.4
            :name edmacs-evil-config--c-x-dispatch
            :docstring ,(format "Decrement number at point (vim's `C-x'), \
or run a registered command when `C-x' is followed by one of: %s."
                                 (mapconcat #'car edmacs-evil-config--c-x-chords ", "))
            ,@(mapcan (lambda (entry) (list (car entry) `(quote ,(cdr entry))))
                      edmacs-evil-config--c-x-chords))
         t)
      'evil-numbers/dec-at-pt)))

(defun edmacs-evil-config-add-c-x-chord (key command)
  "Register COMMAND to run when normal-state `C-x' is followed by KEY.
KEY is a string typed after `C-x' (e.g. \"t p\" or \"v w s\"). This is
the extension point other modules use to reach past the leaf `C-x'
binding this file installs for `evil-numbers/dec-at-pt' -- see the
commentary above `edmacs-evil-config--c-x-chords' for why no other
module should call `define-key' on that keymap entry directly. Safe
to call regardless of load order relative to this file or to
`evil-numbers': the alist entry is recorded immediately, and the
actual keymap rebuild is deferred to once `evil-numbers' has installed
its own initial binding."
  (setf (alist-get key edmacs-evil-config--c-x-chords nil nil #'equal) command)
  (with-eval-after-load 'evil-numbers
    (edmacs-evil-config--rebuild-c-x-binding)))

(use-package evil-numbers
  :after evil
  :config
  ;; Bind in normal state
  (define-key evil-normal-state-map (kbd "C-a") 'evil-numbers/inc-at-pt)
  (edmacs-evil-config--rebuild-c-x-binding))

;; ============================================================================
;; Evil Matchit - Match tags with %
;; ============================================================================

(use-package evil-matchit
  :after evil
  :config
  (global-evil-matchit-mode 1))

;; ============================================================================
;; Evil Visualstar - Search selected text with *
;; ============================================================================

(use-package evil-visualstar
  :after evil
  :config
  (global-evil-visualstar-mode 1))

;; ============================================================================
;; Evil Indent Textobject - Text objects for indentation
;; ============================================================================

(use-package evil-indent-plus
  :after evil
  :config
  (evil-indent-plus-default-bindings))

;; ============================================================================
;; Additional Evil Keybindings
;; ============================================================================

(with-eval-after-load 'evil
  ;; Use visual line motions even outside visual-line-mode buffers
  (evil-global-set-key 'motion "j" 'evil-next-visual-line)
  (evil-global-set-key 'motion "k" 'evil-previous-visual-line)

  ;; Make ESC quit prompts
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit))

;;; evil-config.el ends here
