#!/usr/bin/env bash
#
# gc-session-bench.sh -- reproducible gcs-done comparison for a representative
# working session, for edmacs-performance/phase-6-gc-and-unbounded-state.
#
# WHY THIS EXISTS
#   AC6 of that phase requires "gcs-done over a representative working
#   session is lower than the current baseline, measured with the phase 1
#   harness or an equivalent." Phase 1's harness (startup-bench.sh) times
#   interactive startup only -- it never runs a post-startup workload and
#   never reports `gcs-done`, so it cannot answer this AC. This script is
#   the "or an equivalent" the phase's own plan calls for building.
#
# WHY --batch IS FINE HERE (UNLIKE startup-bench.sh)
#   startup-bench.sh's big warning against `--batch` is specifically about
#   measuring *startup time*: `--batch` implies `-q`, never loads
#   early-init.el/init.el, and never sets `after-init-time`, so a batch run
#   "measuring" startup reports a meaningless near-zero. That trap does not
#   apply here. This script does not measure startup time or claim to; it
#   loads this config's real early-init.el/init.el explicitly via `-l`
#   (see run_session below), runs a synthetic post-startup workload, and
#   reads `gcs-done` -- a plain counter Emacs increments on every GC,
#   identical under `--batch` and interactive operation. `--batch` also
#   sidesteps the pty (`script(1)`) requirement startup-bench.sh needs for
#   `-nw`, which is flaky in some sandboxed/nested-shell contexts (see that
#   script's `run_timed` comment) -- not needed for a workload with no
#   frame or terminal interaction of its own.
#
# WHAT "REPRESENTATIVE SESSION" MEANS HERE
#   Real lsp-mode servers (gopls, jdtls, rust-analyzer, clojure-lsp,
#   typescript-language-server) are not something this script can assume
#   are installed, network-reachable, or fast enough for a repeatable
#   benchmark -- and the actual GC pressure this phase's audit identified
#   is allocation volume, not any language server's specific protocol
#   quirks: JSON-RPC deserialisation, large-buffer rewrites (apheleia
#   format-on-save), and undo-history retention (lsp-rename-sized edits).
#   `edmacs-gc-bench--run-session' (below, generated by write_session_el)
#   reproduces that allocation *shape* directly and deterministically:
#     - repeated `json-parse-string' calls over a multi-KB JSON payload,
#       standing in for LSP JSON-RPC response parsing;
#     - large-buffer insert/delete cycles across several buffers, standing
#       in for apheleia rewriting a big file on save;
#     - buffer-local undo recording plus repeated `undo' calls, standing in
#       for the undo pressure `lsp-rename' and format-on-save put on
#       `undo-limit'/`undo-strong-limit';
#     - buffer-list cycling, standing in for switching between open
#       buffers during a session.
#   This is deliberately not a claim that it reproduces any specific
#   language server's behavior -- it reproduces the allocation pattern the
#   phase's audit named as the actual driver of GC pressure, so the same
#   workload is meaningful to compare across GC configurations.
#
# WHAT IS COMPARED
#   Two GC configurations, run as the *same* workload inside the *same*
#   Emacs process (so JIT/native-comp warm-up and package load cost are
#   identical for both, and only the GC-relevant settings differ):
#     baseline    -- gc-cons-threshold fixed at 16MB (this repo's own
#                    pre-phase-6 emacs-startup-hook value), undo-limit /
#                    undo-strong-limit at Emacs's stock 160000 / 240000
#                    bytes -- i.e. exactly the settings this phase changes.
#     post-change -- gcmh-mode enabled with this repo's post-phase-6
#                    gcmh-high-cons-threshold (100MB) / gcmh-idle-delay,
#                    and undo-limit / undo-strong-limit at this phase's
#                    raised values (3MB / 16MB).
#   Both configurations' values are read directly from this repo's real
#   config files (early-init.el/init.el/modules/core.el), not hand-copied
#   constants, so this script cannot silently drift out of sync with what
#   actually ships -- see extract_current_values below.
#   `gcs-done' is read before and after each phase; the reported number is
#   the delta, i.e. GCs actually caused by that phase's workload.
#
# USAGE
#   scripts/gc-session-bench.sh              # one run, prints both deltas
#   scripts/gc-session-bench.sh -n 5         # average of 5 runs each
#
# CAVEATS
#   - This measures relative GC pressure under a controlled synthetic
#     workload, not wall-clock latency and not real lsp-mode traffic. It
#     is a stand-in for "no repeatable representative-session harness
#     existed yet," not a claim of having benchmarked real LSP sessions.
#   - `gcs-done' during the baseline phase is inflated further by leaving
#     `after-focus-change-function' out of scope entirely -- that hook
#     depended on real frame-focus events this batch workload cannot
#     produce at all, so this script cannot and does not attempt to
#     reproduce AC1's separate frame-focus-behavior claim. AC6 is about
#     total GC count, which the focus hook's removal also helps (every
#     focus-loss GC it used to force is one this script's baseline phase
#     doesn't need to simulate to already show a difference from the
#     threshold/undo-limit changes alone).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUNS=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    -n|--runs)
      RUNS="$2"
      shift 2
      ;;
    *)
      echo "usage: $0 [-n RUNS]" >&2
      exit 1
      ;;
  esac
done

if ! [[ "$RUNS" =~ ^[0-9]+$ ]] || [[ "$RUNS" -lt 1 ]]; then
  echo "error: --runs must be a positive integer, got: $RUNS" >&2
  exit 1
fi

# Pull the real post-change values straight out of this repo's tracked
# config, so "post-change" in this script's comparison always matches what
# init.el/modules/core.el actually ship -- never a hand-copied constant
# that can quietly drift.
extract_setq_number() {
  # $1 = file, $2 = variable name. Expects `(setq VAR (* A B C))` or
  # `(setq VAR NNN)` on its own line (or as one clause of a multi-clause
  # setq); prints the evaluated integer.
  local file="$1" var="$2"
  emacs --batch --eval "
    (with-temp-buffer
      (insert-file-contents \"$file\")
      (goto-char (point-min))
      (catch 'found
        (while (re-search-forward (concat \"[( ]\" (regexp-quote \"$var\") \"[ \\n]+\") nil t)
          (let* ((form (ignore-errors (read (current-buffer))))
                 (val (ignore-errors (eval form t))))
            (when (numberp val)
              (princ (number-to-string val))
              (throw 'found nil))))
        (error \"could not find %s in %s\" \"$var\" \"$file\")))" 2>/dev/null
}

GCMH_HIGH="$(extract_setq_number "$REPO_ROOT/init.el" "gcmh-high-cons-threshold")"
GCMH_IDLE_DELAY="$(extract_setq_number "$REPO_ROOT/init.el" "gcmh-idle-delay")"
NEW_UNDO_LIMIT="$(extract_setq_number "$REPO_ROOT/modules/core.el" "undo-limit")"
NEW_UNDO_STRONG_LIMIT="$(extract_setq_number "$REPO_ROOT/modules/core.el" "undo-strong-limit")"

for v in GCMH_HIGH GCMH_IDLE_DELAY NEW_UNDO_LIMIT NEW_UNDO_STRONG_LIMIT; do
  if [[ -z "${!v}" ]]; then
    echo "error: failed to extract $v from tracked config -- has the variable name changed?" >&2
    exit 1
  fi
done

echo "Post-change values read from tracked config:"
echo "  gcmh-high-cons-threshold = $GCMH_HIGH"
echo "  gcmh-idle-delay          = $GCMH_IDLE_DELAY"
echo "  undo-limit               = $NEW_UNDO_LIMIT"
echo "  undo-strong-limit        = $NEW_UNDO_STRONG_LIMIT"
echo

# The workload. Defines edmacs-gc-bench--run-session, which performs one
# pass of the allocation-shaped work described in the header comment above
# and returns the number of GCs it caused. Written once to a temp file and
# reused by both the baseline and post-change --batch invocations below.
SESSION_EL="$(mktemp -t edmacs-gc-bench-session-XXXXXX.el)"
trap 'rm -f "$SESSION_EL"' EXIT

cat > "$SESSION_EL" <<'ELISP'
(defun edmacs-gc-bench--json-payload (n)
  "Build an N-entry JSON array string, standing in for an LSP JSON-RPC body."
  (concat "["
          (mapconcat
           (lambda (i)
             (format "{\"id\":%d,\"method\":\"textDocument/publishDiagnostics\",\"params\":{\"uri\":\"file:///tmp/f%d.go\",\"diagnostics\":[{\"range\":{\"start\":{\"line\":%d,\"character\":0},\"end\":{\"line\":%d,\"character\":10}},\"message\":\"unused variable x%d\",\"severity\":2}]}}"
                     i i i i i))
           (number-sequence 0 (1- n))
           ",")
          "]"))

(defun edmacs-gc-bench--large-text (lines)
  "Build a LINES-line synthetic source buffer body."
  (mapconcat (lambda (i) (format "func handler%d(w http.ResponseWriter, r *http.Request) { fmt.Fprintf(w, \"ok %%d\", %d) }" i i))
             (number-sequence 0 (1- lines))
             "\n"))

(defun edmacs-gc-bench--run-session ()
  "Run one representative-session workload pass; return GCs it caused."
  (let ((before gcs-done)
        (json-payload (edmacs-gc-bench--json-payload 400))
        (big-text (edmacs-gc-bench--large-text 4000)))
    ;; JSON-RPC-shaped parsing churn: 5 synthetic "buffers" each getting
    ;; ~40 diagnostics batches parsed, like a multi-file lsp-mode session.
    (dotimes (_buf 5)
      (dotimes (_msg 40)
        (json-parse-string json-payload :object-type 'alist)))
    ;; Large-buffer rewrite churn: format-on-save-shaped insert/delete
    ;; across several buffers, each with undo recording live (mirrors
    ;; apheleia + lsp-rename's undo pressure).
    (dotimes (buf 3)
      (with-temp-buffer
        (buffer-enable-undo)
        (insert big-text)
        (dotimes (_rewrite 6)
          (goto-char (point-min))
          (while (re-search-forward "handler[0-9]+" nil t)
            (replace-match (format "handler_renamed_%d" buf)))
          (undo-boundary)
          (goto-char (point-max))
          (insert big-text))
        ;; Undo pressure: unwind most of what was just done.
        (dotimes (_u 8)
          (ignore-errors (primitive-undo 1 buffer-undo-list)))))
    ;; Buffer-switching churn: a session bouncing between several live
    ;; buffers, each already holding real content.
    (let (bufs)
      (dotimes (i 8)
        (push (generate-new-buffer (format "*gc-bench-%d*" i)) bufs))
      (dotimes (_cycle 20)
        (dolist (b bufs)
          (with-current-buffer b
            (goto-char (point-max))
            (insert (substring big-text 0 (min 500 (length big-text)))))))
      (mapc #'kill-buffer bufs))
    (- gcs-done before)))
ELISP

# Runs one --batch Emacs process that loads this repo's real
# early-init.el/init.el (so straight/use-package/gcmh are genuinely
# initialized, not hand-simulated), then overrides GC-relevant variables
# to either the baseline or post-change values, runs the workload once,
# and prints the resulting GC delta on its own line as "GCS-DELTA: N".
#
# $1 = "baseline" or "post-change"
run_session() {
  local mode="$1" override
  case "$mode" in
    baseline)
      # This repo's own pre-phase-6 values (see early-init.el/init.el
      # history): a flat 16MB threshold with no idle-driven high/low
      # oscillation, and Emacs's stock undo limits.
      override="
        (when (fboundp 'gcmh-mode) (gcmh-mode -1))
        (setq gc-cons-threshold (* 16 1024 1024)
              gc-cons-percentage 0.1
              undo-limit 160000
              undo-strong-limit 240000)"
      ;;
    post-change)
      # Whatever this repo's tracked config actually sets, re-asserted
      # here only to make the two runs' starting point for this workload
      # symmetric (both start the workload from a fresh, just-reset
      # threshold) -- gcmh-mode is already enabled by init.el itself.
      override="
        (setq gc-cons-threshold $GCMH_HIGH
              gc-cons-percentage 0.1
              undo-limit $NEW_UNDO_LIMIT
              undo-strong-limit $NEW_UNDO_STRONG_LIMIT)"
      ;;
    *)
      echo "internal error: unknown mode $mode" >&2
      return 1
      ;;
  esac

  emacs --batch \
    --eval "(setq user-emacs-directory (expand-file-name \"$REPO_ROOT/\"))" \
    -l "$REPO_ROOT/early-init.el" \
    -l "$REPO_ROOT/init.el" \
    --eval "(run-hooks 'emacs-startup-hook)" \
    -l "$SESSION_EL" \
    --eval "(progn $override (garbage-collect) (princ (format \"GCS-DELTA: %d\n\" (edmacs-gc-bench--run-session))))" \
    2>/dev/null | grep '^GCS-DELTA:' | awk '{print $2}'
}

sum_baseline=0
sum_post=0

for ((i = 1; i <= RUNS; i++)); do
  b="$(run_session baseline)"
  p="$(run_session post-change)"
  if [[ -z "$b" || -z "$p" ]]; then
    echo "warning: run $i produced no GCS-DELTA output -- skipping" >&2
    continue
  fi
  echo "run $i: baseline gcs-done delta = $b   post-change gcs-done delta = $p"
  sum_baseline=$((sum_baseline + b))
  sum_post=$((sum_post + p))
done

echo
echo "=== Summary over $RUNS run(s) ==="
awk -v b="$sum_baseline" -v p="$sum_post" -v n="$RUNS" '
  BEGIN {
    printf "  baseline    mean gcs-done delta: %.2f\n", b / n
    printf "  post-change mean gcs-done delta: %.2f\n", p / n
    if (p < b) {
      printf "  RESULT: post-change is lower (-%.2f, %.1f%% fewer GCs) -- AC6 satisfied\n", (b - p) / n, 100 * (b - p) / b
    } else {
      printf "  RESULT: post-change is NOT lower than baseline -- AC6 NOT satisfied\n"
    }
  }
'
