#!/usr/bin/env bash
#
# install-emacs-client-app.sh -- build ~/Applications/Emacs Client.app, a Dock
# launcher that connects to the Emacs daemon instead of starting a new Emacs.
#
# Clicking Emacs.app always launches a fresh instance, and the daemon has no
# Dock presence until it owns a frame, so a wrapper app is the only way to
# make the Dock icon talk to the daemon. The wrapper focuses an existing GUI
# frame, or creates one with `emacsclient -c' (which is what triggers the
# desktop layout restore in modules/sessions.el), starting the emacs-plus
# launchd service first if the daemon is down. It uses Emacs's own icon and
# is marked LSUIElement so it never shows as a second running app.
#
# Finder "Open With" is not supported: a script bundle cannot receive
# open-document Apple events.
#
# USAGE
#   scripts/install-emacs-client-app.sh
#   Rerun after a `brew upgrade' if the Emacs.app path changes.

set -euo pipefail

EMACS_APP="$(/opt/homebrew/bin/brew --prefix emacs-plus@31)/Emacs.app"
SERVICE="emacs-plus@31"
APP_DIR="$HOME/Applications/Emacs Client.app"

if [[ ! -f "$EMACS_APP/Contents/Resources/Emacs.icns" ]]; then
  echo "error: $EMACS_APP not found; is emacs-plus@31 installed?" >&2
  exit 1
fi

rm -rf "$APP_DIR"
mkdir -p "$APP_DIR/Contents/MacOS" "$APP_DIR/Contents/Resources"
cp "$EMACS_APP/Contents/Resources/Emacs.icns" "$APP_DIR/Contents/Resources/Emacs.icns"

cat > "$APP_DIR/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>Emacs Client</string>
  <key>CFBundleDisplayName</key><string>Emacs</string>
  <key>CFBundleIdentifier</key><string>org.edmacs.emacs-client</string>
  <key>CFBundleVersion</key><string>1</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>emacs-client</string>
  <key>CFBundleIconFile</key><string>Emacs</string>
  <key>LSUIElement</key><true/>
  <key>LSMinimumSystemVersion</key><string>12.0</string>
</dict>
</plist>
EOF

cat > "$APP_DIR/Contents/MacOS/emacs-client" <<EOF
#!/bin/bash
# Generated by scripts/install-emacs-client-app.sh in the edmacs repo.
export PATH="/opt/homebrew/bin:\$PATH"
# Dock-launched apps may lack TMPDIR; emacsclient derives the socket dir from it.
export TMPDIR="\${TMPDIR:-\$(getconf DARWIN_USER_TEMP_DIR)}"

has_gui_frame='(and (seq-find (function display-graphic-p) (frame-list)) t)'
focus_frame='(let ((f (seq-find (function display-graphic-p) (frame-list)))) (raise-frame f) (select-frame-set-input-focus f))'

if ! emacsclient -e t >/dev/null 2>&1; then
  brew services start $SERVICE >/dev/null 2>&1
  for _ in \$(seq 1 60); do
    emacsclient -e t >/dev/null 2>&1 && break
    sleep 0.5
  done
fi

if [[ "\$(emacsclient -e "\$has_gui_frame" 2>/dev/null)" == "t" ]]; then
  exec emacsclient -n -e "\$focus_frame"
fi
exec emacsclient -n -c
EOF
chmod +x "$APP_DIR/Contents/MacOS/emacs-client"

codesign --force --sign - "$APP_DIR" >/dev/null 2>&1 || true
echo "installed $APP_DIR"
